name: SharedBans
main: cz.majncraft.sharedbans.SharedBans
version: 1.0
author: Karel Tuma <karel.tuma@gmail.com>
depend: [McGroovy]
description: >
    DNSBL based shared bans
commands:
    sbex:
        description: Add exception from shared bans
        usage: |
            Incorrect usage of /<command>. Examples:
            /<command> foobar - exempt nick foobar from all kinds of bans
    sbunex:
        description: Remove exception from shared bans
        usage: |
            Incorrect usage of /<command>. Examples:
            /<command> foobar - remove exempt for nick foobar
    sbreload:
        description: Reload SharedBans config
        usage: |
            Incorrect usage of /<command>. Examples:
            /sbreload
    sbcheck:
        description: Lookup bans for given nick or IP address.
        usage: |
            Incorrect usage of /<command>. Examples:
            /sbcheck PlayerName
            /sbcheck 1.2.3.4
