name: SharedBans
main: cz.majncraft.sharedbans.SharedBans
version: 1.1
author: Karel Tuma <karel.tuma@gmail.com>
softdepend: [McGroovy]
description: DNSBL based shared bans
commands:
    sbex:
        permission: sb.sbex
        description: Add exception from shared bans
        usage: /<command> foobar - exempt nick foobar from all kinds of bans
    sbunex:
        permission: sb.sbunex
        description: Remove exception from shared bans
        usage: /<command> foobar - remove exempt for nick foobar
    sbreload:
        permission: sb.sbreload
        description: Reload SharedBans config
        usage: /sbreload - reload SharedBans/config.yml
    sbcheck:
        permission: sb.sbcheck
        description: Lookup bans for given nick or IP address.
        usage: |
            Lookup bans for given nick or IP address.
            /sbcheck PlayerName
            /sbcheck 1.2.3.4
